// 레트로 UI 픽셀 아이콘 — 16×16 격자, 한 글자 = 한 칸.
// 이모지는 운영체제마다 모양이 달라져 쓰지 않는다. 색은 아래 팔레트 안에서만 고른다
// (파스텔 블루·라일락 바탕 + 핑크·보라·민트 포인트).

export const PIXEL_PALETTE: Record<string, string> = {
  k: '#26306b', // 외곽선 (짙은 남색)
  w: '#ffffff',
  s: '#dbe8ff', // 하늘 옅음
  b: '#8fb6ff', // 하늘
  B: '#4a7fe6', // 파랑
  D: '#2f58c4', // 파랑 짙음
  l: '#e8e0ff', // 라일락 옅음
  L: '#b9a3f5', // 라일락
  p: '#ffc4e1', // 핑크 옅음
  P: '#ff78b8', // 핑크
  v: '#c064e0', // 보라
  m: '#aef2e0', // 민트 옅음
  M: '#3fc9a8', // 민트
  n: '#1f9b82', // 민트 짙음
  o: '#ffd6a6', // 복숭아
  O: '#f5a860', // 주황
  y: '#ffe98a', // 노랑
  r: '#ff5f7a', // 하트 빨강
  R: '#d63a5c', // 하트 그늘
  g: '#b8c2e6', // 회청
}

const ARROW_LEFT = [
  '................',
  '................',
  '................',
  '.....kk.........',
  '....kBk.........',
  '...kBBkkkkkkkk..',
  '..kBBBBBBBBBBBk.',
  '.kBBBBBBBBBBBBk.',
  '..kBBBBBBBBBBBk.',
  '...kBBkkkkkkkk..',
  '....kBk.........',
  '.....kk.........',
  '................',
  '................',
  '................',
  '................',
]

export const PIXEL_ICONS = {
  heart: [
    '................',
    '..kkkk....kkkk..',
    '.krrrrk..krrrrk.',
    'krwwrrrkkrrrrrRk',
    'krwrrrrrrrrrrrRk',
    'krrrrrrrrrrrrrRk',
    'krrrrrrrrrrrrrRk',
    '.krrrrrrrrrrrRk.',
    '..krrrrrrrrrRk..',
    '...krrrrrrrRk...',
    '....krrrrrRk....',
    '.....krrrRk.....',
    '......krRk......',
    '.......kk.......',
    '................',
    '................',
  ],
  folder: [
    '................',
    '................',
    '.kkkkk..........',
    'kyyyyyk.........',
    'kyyyyyykkkkkkkk.',
    'kyyyyyyyyyyyyyyk',
    'koooooooooooooOk',
    'koooooooooooooOk',
    'koooooooooooooOk',
    'koooooooooooooOk',
    'koooooooooooooOk',
    'koooooooooooooOk',
    'kOOOOOOOOOOOOOOk',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  camera: [
    '................',
    '................',
    '.....kkkkkk.....',
    '....kggggggk....',
    '.kkkkkkkkkkkkkk.',
    'kwssssssssssPPgk',
    'ksssskkkkkksssgk',
    'kssskBBBBBBkssgk',
    'ksskBBwwBBBBksgk',
    'ksskBBwBBBBBksgk',
    'ksskBBBBBBDBksgk',
    'ksskBBBBBDDBksgk',
    'kssskBBBDDBkssgk',
    'ksssskkkkkksssgk',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  computer: [
    '................',
    '.kkkkkkkkkkkkkk.',
    'kmmmmmmmmmmmmmnk',
    'kmkkkkkkkkkkkmnk',
    'kmkBBBBBBBBBkmnk',
    'kmkBbBBBBBBBkmnk',
    'kmkBBBBBBBBBkmnk',
    'kmkBBBBBBBBBkmnk',
    'kmkkkkkkkkkkkmnk',
    'kmmmmmmmmmmmMMnk',
    '.knnnnnnnnnnnnk.',
    '...kkkkkkkkkk...',
    '..kmmmmmmmmmmk..',
    '.kmwmwmwmwmwmnk.',
    '.knnnnnnnnnnnnk.',
    '..kkkkkkkkkkkk..',
  ],
  file: [
    '................',
    '..kkkkkkkkk.....',
    '..kwwwwwwwkk....',
    '..kwwwwwwwkgk...',
    '..kwwwwwwwkggk..',
    '..kwwwwwwwkkkkk.',
    '..kwBBBBBBBwwwk.',
    '..kwwwwwwwwwwwk.',
    '..kwLLLLLLLLwwk.',
    '..kwwwwwwwwwwwk.',
    '..kwBBBBBBBBBwk.',
    '..kwwwwwwwwwwwk.',
    '..kwPPPPPwwwwwk.',
    '..kwwwwwwwwwwwk.',
    '..kkkkkkkkkkkkk.',
    '................',
  ],
  window: [
    '................',
    'kkkkkkkkkkkkkkkk',
    'kDDBBBBBbbbbbwwk',
    'kDDBBBBBbbbbbwwk',
    'kkkkkkkkkkkkkkkk',
    'kwwwwwwwwwwwwwgk',
    'kwsssssswwwwwwgk',
    'kwwwwwwwwwwwwwgk',
    'kwLLLLLLLLLwwwgk',
    'kwwwwwwwwwwwwwgk',
    'kwssssswwwwwwwgk',
    'kwwwwwwwwwwwwwgk',
    'kwwwwwwwwwwwwwgk',
    'kggggggggggggggk',
    'kkkkkkkkkkkkkkkk',
    '................',
  ],
  printer: [
    '................',
    '....kkkkkkkk....',
    '....kwwwwwwk....',
    '....kwBBBBwk....',
    '..kkkkkkkkkkkk..',
    '.klllllllllllLk.',
    'klllllllllllMlLk',
    'klllllllllllllLk',
    'kLLLLLLLLLLLLLLk',
    'kLLkkkkkkkkkkLLk',
    '.kkkwwwwwwwwkkk.',
    '...kwwwwwwwwk...',
    '...kwPPPPwwwk...',
    '...kwwwwwwwwk...',
    '...kkkkkkkkkk...',
    '................',
  ],
  floppy: [
    '................',
    '.kkkkkkkkkkkkk..',
    '.kBkwwwwwwwwkBk.',
    '.kBkwwwwkkwwkBk.',
    '.kBkwwwwkkwwkBBk',
    '.kBkkkkkkkkkkBBk',
    '.kBBBBBBBBBBBBBk',
    '.kBBkkkkkkkkkBBk',
    '.kBkssssssssskBk',
    '.kBksPPPPPPsskBk',
    '.kBkssssssssskBk',
    '.kBksLLLLLssskBk',
    '.kBkssssssssskBk',
    '.kDkkkkkkkkkkkDk',
    '..kkkkkkkkkkkkk.',
    '................',
  ],
  qr: [
    'kkkkk..k.k.kkkkk',
    'kwwwk.k..k.kwwwk',
    'kwkwk..kk..kwkwk',
    'kwwwk.k.k.kkwwwk',
    'kkkkk.k.k..kkkkk',
    '......kk.k......',
    'k.kk.k..kk.k.kk.',
    '.k..kk.k..k.kk.k',
    'kk.k..kk.kk.k..k',
    '..k.kk..k..kk.k.',
    '......k.kk.k.kk.',
    'kkkkk..kk.k..k.k',
    'kwwwk.k..k.kk..k',
    'kwkwk..kk.k.kk.k',
    'kwwwk.k.k..k..kk',
    'kkkkk.kk.kk.k.k.',
  ],
  phone: [
    '....kkkkkkkk....',
    '...kLLLkkLLLk...',
    '...kLkkkkkkLk...',
    '...kLksbbbkLk...',
    '...kLkbwbbkLk...',
    '...kLkbbbbkLk...',
    '...kLkbPPbkLk...',
    '...kLkbPPbkLk...',
    '...kLkbbbbkLk...',
    '...kLkbbbskLk...',
    '...kLkkkkkkLk...',
    '...kLLLLLLLLk...',
    '...kLLLkkLLLk...',
    '...kLLLLLLLLk...',
    '....kkkkkkkk....',
    '................',
  ],
  duo: [
    '................',
    '...kkkk...kkkk..',
    '..kooook.kooook.',
    '..kooook.kooook.',
    '..kooook.kooook.',
    '...kkkk...kkkk..',
    '..kkBBkk.kkvvkk.',
    '.kBBBBBBkvvvvvvk',
    '.kBBBBBBkvvvvvvk',
    '.kBBBBBBkvvvvvvk',
    '.kkkkkkkkkkkkkkk',
    '.....kk.kk......',
    '....krrkrrk.....',
    '....krrrrrk.....',
    '.....krrrk......',
    '......krk.......',
  ],
  sparkle: [
    '................',
    '.......kk.......',
    '.......kk.......',
    '......kyyk......',
    '......kyyk......',
    '.....kyyyyk.....',
    '..kkkyywwyykkk..',
    'kkyyyywwwwyyyykk',
    'kkyyyywwwwyyyykk',
    '..kkkyywwyykkk..',
    '.....kyyyyk.....',
    '......kyyk......',
    '......kyyk......',
    '.......kk.......',
    '.......kk.......',
    '................',
  ],
  star: [
    '.......kk.......',
    '......kyyk......',
    '......kyyk......',
    '.....kyyyyk.....',
    'kkkkkkyyyykkkkkk',
    'kyyyyyyyyyyyyyyk',
    '.kyyyyyyyyyyyyk.',
    '..kyyyyyyyyyyk..',
    '...kyyyyyyyyk...',
    '...kyyyyyyyyk...',
    '..kyyyykkyyyyk..',
    '..kyyyk..kyyyk..',
    '.kyyyk....kyyyk.',
    '.kyyk......kyyk.',
    '.kkk........kkk.',
    '................',
  ],
  check: [
    '................',
    '................',
    '............kk..',
    '...........kMMk.',
    '..........kMMk..',
    '.........kMMk...',
    '..kk....kMMk....',
    '.kMMk..kMMk.....',
    '..kMMkkMMk......',
    '...kMMMMk.......',
    '....kMMk........',
    '.....kk.........',
    '................',
    '................',
    '................',
    '................',
  ],
  warning: [
    '................',
    '.......kk.......',
    '......kyyk......',
    '......kyyk......',
    '.....kyyyyk.....',
    '.....kykkyk.....',
    '....kyykkyyk....',
    '....kyykkyyk....',
    '...kyyykkyyyk...',
    '...kyyykkyyyk...',
    '..kyyyyyyyyyyk..',
    '..kyyyykkyyyyk..',
    '.kyyyyykkyyyyyk.',
    '.kyyyyyyyyyyyyk.',
    'kkkkkkkkkkkkkkkk',
    '................',
  ],
  hourglass: [
    '................',
    '..kkkkkkkkkkkk..',
    '..kLLLLLLLLLLk..',
    '...kwwwwwwwwk...',
    '...kwyyyyyywk...',
    '....kwyyyywk....',
    '.....kwyywk.....',
    '......kyyk......',
    '......kwwk......',
    '.....kwwywk.....',
    '....kwwwywwk....',
    '...kwwwyyywwk...',
    '...kwyyyyyywk...',
    '..kLLLLLLLLLLk..',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  globe: [
    '................',
    '.....kkkkkk.....',
    '...kkbbMMbbkk...',
    '..kbbbMMMbbbbk..',
    '.kbbbMMMMbbbbbk.',
    '.kbbMMMMbbbMMbk.',
    'kbbbbMMbbbMMMbbk',
    'kbbbbbbbbbMMMbbk',
    'kbbMMbbbbbbMbbbk',
    'kbMMMMbbbbbbbbbk',
    '.kbMMMMbbbbbbbk.',
    '.kbbMMbbbbMbbbk.',
    '..kbbbbbbMMbbk..',
    '...kkbbbbbbkk...',
    '.....kkkkkk.....',
    '................',
  ],
  lock: [
    '................',
    '.....kkkkkk.....',
    '....kggggggk....',
    '...kgk....kgk...',
    '...kgk....kgk...',
    '...kgk....kgk...',
    '..kkkkkkkkkkkk..',
    '..kyyyyyyyyyOk..',
    '..kyyyykkyyyOk..',
    '..kyyyykkyyyOk..',
    '..kyyyyykyyyOk..',
    '..kyyyyykyyyOk..',
    '..kyyyyyyyyyOk..',
    '..kOOOOOOOOOOk..',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  home: [
    '................',
    '.......kk.......',
    '......kPPk......',
    '.....kPPPPk.....',
    '....kPPPPPPk....',
    '...kPPPPPPPPk...',
    '..kPPPPPPPPPPk..',
    '.kkkkkkkkkkkkkk.',
    '..kwwwwwwwwwwk..',
    '..kwbbwwwkkkwk..',
    '..kwbbwwwkykwk..',
    '..kwwwwwwkykwk..',
    '..kwwwwwwkykwk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  arrowLeft: ARROW_LEFT,
  arrowRight: ARROW_LEFT.map((row) => [...row].reverse().join('')),
  photo: [
    '................',
    'kkkkkkkkkkkkkkkk',
    'kwwwwwwwwwwwwwwk',
    'kwssssssssssyywk',
    'kwsssssssssyyywk',
    'kwsssssssssssswk',
    'kwsssssMsssssswk',
    'kwssssMMMssssswk',
    'kwsssMMMMMssMswk',
    'kwssMMMMMMMMMMwk',
    'kwsMMnMMMMMnMMwk',
    'kwMMMMMMMMMMMMwk',
    'kwwwwwwwwwwwwwwk',
    'kkkkkkkkkkkkkkkk',
    '................',
    '................',
  ],
  bottle: [
    '................',
    '......kkkk......',
    '......kPPk......',
    '......kPPk......',
    '.....kkkkkk.....',
    '......kwwk......',
    '...kkkkkkkkkk...',
    '..kllllllllllk..',
    '..klwwllllllLk..',
    '..klwlllllllLk..',
    '..kllllvvlllLk..',
    '..kllllvvlllLk..',
    '..klllllllllLk..',
    '..kLLLLLLLLLLk..',
    '...kkkkkkkkkk...',
    '................',
  ],
  person: [
    '................',
    '......kkkk......',
    '.....kooook.....',
    '....koooooOk....',
    '....koooooOk....',
    '....koooooOk....',
    '.....kooOOk.....',
    '......kkkk......',
    '....kkBBBBkk....',
    '...kBBBBBBBBk...',
    '..kBBBBBBBBBBk..',
    '..kBBBBBBBBBDk..',
    '..kBBBBBBBBBDk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  palette: [
    '................',
    '....kkkkkkk.....',
    '..kkwwwwwwwkk...',
    '.kwPPwwwwMMwwk..',
    '.kwPPwwwwMMwwwk.',
    'kwwwwwwwwwwwwwwk',
    'kwyywwwkkwwwvvwk',
    'kwyywwk..kwwvvwk',
    'kwwwwwwkkwwwwwwk',
    'kwBBwwwwwwwwwwk.',
    '.kBBwwwwwwwwwk..',
    '..kkwwwwwwwkk...',
    '....kkkkkkk.....',
    '................',
    '................',
    '................',
  ],
  close: [
    '................',
    '................',
    '................',
    '...DD......DD...',
    '...DDD....DDD...',
    '....DDD..DDD....',
    '.....DDDDDD.....',
    '......DDDD......',
    '......DDDD......',
    '.....DDDDDD.....',
    '....DDD..DDD....',
    '...DDD....DDD...',
    '...DD......DD...',
    '................',
    '................',
    '................',
  ],
  backspace: [
    '................',
    '................',
    '................',
    '....kkkkkkkkkkk.',
    '...kwwwwwwwwwwk.',
    '..kwwDwwwwDwwwk.',
    '.kwwwwDwwDwwwwk.',
    'kwwwwwwDDwwwwwk.',
    'kwwwwwwDDwwwwwk.',
    '.kwwwwDwwDwwwwk.',
    '..kwwDwwwwDwwwk.',
    '...kwwwwwwwwwwk.',
    '....kkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ],
  shift: [
    '................',
    '.......kk.......',
    '......kbbk......',
    '.....kbbbbk.....',
    '....kbbbbbbk....',
    '...kbbbbbbbbk...',
    '..kkkkbbbbkkkk..',
    '.....kbbbbk.....',
    '.....kbbbbk.....',
    '.....kbbbbk.....',
    '.....kbbbbk.....',
    '.....kkkkkk.....',
    '................',
    '................',
    '................',
    '................',
  ],
} as const

export type PixelIconName = keyof typeof PIXEL_ICONS
